### ISSUE TITLE
Click-dragging to move circle causes stuck circle when unclicking outside of circle's box/bounds

### ISSUE THREAD

**Issue by elanhickler** [elanhickler/MyReaperPlugin#1]
If you click-drag inside a box and unclick outside of a circle's box (say another box or completely outside the GUI), the circle remains "clicked" and follows the mouse indefinitely. If you play your cards right you can get circles following the mouse in all 4 boxes.

**Comment by Xenakios** [comment]
Possibly fixed in the LiceControl base class code. However, like mentioned in the commit msg, this may be a deeper issue to deal with.
